import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType } from 'docx';

export async function buildPaintingDocx(painting) {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: 'ArtMind AI Portal — Curator Sheet',
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 120 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Official Artwork Catalog & Intelligence Record',
                italics: true,
                color: '8C7355',
                size: 20
              })
            ],
            spacing: { after: 300 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: painting.title || 'Untitled Artwork',
                bold: true,
                size: 32,
                color: '1A1918'
              })
            ]
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Artist: ${painting.artist || 'Unknown'} | Date: ${painting.dateDisplay || 'Undated'}`,
                italics: true,
                size: 24,
                color: '555555'
              })
            ],
            spacing: { after: 240 }
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Category', bold: true })] })] }),
                  new TableCell({ children: [new Paragraph({ text: painting.category || 'N/A' })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Style', bold: true })] })] }),
                  new TableCell({ children: [new Paragraph({ text: painting.style || 'N/A' })] })
                ]
              }),
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Medium', bold: true })] })] }),
                  new TableCell({ children: [new Paragraph({ text: painting.medium || 'N/A' })] }),
                  new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Surface', bold: true })] })] }),
                  new TableCell({ children: [new Paragraph({ text: painting.surface || 'N/A' })] })
                ]
              })
            ]
          }),
          new Paragraph({
            text: 'Overview & Description',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 360, after: 120 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: (painting.description || 'No description provided.').replace(/<[^>]*>?/gm, ''),
                size: 22
              })
            ],
            spacing: { after: 240 }
          }),
          new Paragraph({
            text: 'Gemini AI Curator Summary',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 240, after: 120 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: painting.aiSummary || 'Curator summary pending generation.',
                italics: true,
                size: 22,
                color: '2C2A29'
              })
            ],
            spacing: { after: 400 }
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'Generated by ArtMind AI Portal',
                size: 16,
                color: '999999'
              })
            ]
          })
        ]
      }
    ]
  });

  return await Packer.toBuffer(doc);
}
