import { jsPDF } from 'jspdf';

export function buildPaintingPDF(painting) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Background tint
  doc.setFillColor(247, 244, 238);
  doc.rect(0, 0, 210, 297, 'F');

  // Header border bar
  doc.setFillColor(212, 175, 55); // Brass/gold accent
  doc.rect(15, 15, 180, 2, 'F');

  // Title & Subtitle
  doc.setFont('times', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(26, 25, 24);
  doc.text('ArtMind AI Portal — Curator Sheet', 15, 26);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(140, 115, 85);
  doc.text('Official Artwork Catalog & Intelligence Record', 15, 32);

  // Divider
  doc.setDrawColor(232, 226, 213);
  doc.line(15, 36, 195, 36);

  // Artwork Header
  doc.setFont('times', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(26, 25, 24);
  doc.text(painting.title || 'Untitled Artwork', 15, 48);

  doc.setFont('times', 'italic');
  doc.setFontSize(14);
  doc.setTextColor(100, 90, 80);
  doc.text(`By ${painting.artist || 'Unknown Artist'} (${painting.dateDisplay || 'Undated'})`, 15, 56);

  // Metadata Box
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(220, 215, 200);
  doc.roundedRect(15, 63, 180, 45, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(26, 25, 24);

  const labels = [
    ['Category:', painting.category || 'N/A'],
    ['Style:', painting.style || 'N/A'],
    ['Medium:', painting.medium || 'N/A'],
    ['Surface:', painting.surface || 'N/A'],
    ['Color Theme:', painting.colorTheme || 'N/A'],
    ['Popularity Rating:', `${painting.popularity || 0} Points`]
  ];

  labels.forEach((item, index) => {
    const col = index % 2 === 0 ? 20 : 105;
    const row = 72 + Math.floor(index / 2) * 11;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(140, 115, 85);
    doc.text(item[0], col, row);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
    doc.text(item[1], col + 35, row);
  });

  // Description Section
  let currentY = 118;
  if (painting.description) {
    doc.setFont('times', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(26, 25, 24);
    doc.text('Artwork Overview & Description', 15, currentY);
    currentY += 6;

    doc.setFont('times', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const splitDesc = doc.splitTextToSize(painting.description.replace(/<[^>]*>?/gm, ''), 180);
    doc.text(splitDesc, 15, currentY);
    currentY += splitDesc.length * 5 + 6;
  }

  // AI Curator Summary Section
  doc.setFont('times', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(180, 130, 30);
  doc.text('Gemini AI Curator Insights', 15, currentY);
  currentY += 6;

  doc.setFillColor(255, 253, 248);
  doc.setDrawColor(212, 175, 55);
  
  const summaryText = painting.aiSummary || 'Curator analysis pending.';
  const splitSummary = doc.splitTextToSize(summaryText, 170);
  const boxHeight = Math.max(25, splitSummary.length * 5.5 + 8);

  doc.roundedRect(15, currentY, 180, boxHeight, 2, 2, 'FD');

  doc.setFont('times', 'italic');
  doc.setFontSize(10.5);
  doc.setTextColor(30, 30, 30);
  doc.text(splitSummary, 20, currentY + 7);

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by ArtMind AI Portal — All rights reserved.', 15, 285);
  doc.text(`Document ID: AM-${painting._id || '0000'}`, 150, 285);

  return doc.output('arraybuffer');
}
